workflows:
  my-workflow:
    environment:
      groups:
        - sdk
      java: 17
    scripts:
      - name: Setup File
#        script: echo $GOOGLE_SERVICES | base64 --decode > $FCI_BUILD_DIR/app
        script: ls $FCI_BUILD_DIR
#        script: |
#          sh "xcode-select --install"
#          echo $GOOGLE_SERVICES
#          sh "certutil -decode GOOGLE_SERVICES google-services.json"
      - name: Clean Gradle Cache
        script: fastlane runClean
      - name: Run Unit Test
        script: fastlane runUnitTest
      - name: run UI Test
        script: echo "UI Test"
      - name: build
        script: fastlane runBuildApk
