workflows:
  my-workflow:
    environment:
      groups:
        - sdk
      java: 17
    scripts:
      - name: Create File
        script: | 
          echo $GOOGLE_SERVICES | base64 --decode > google-services.json
      - name: Setup File
        script: |
          mv $FCI_BUILD_DIR/google-services.json $FCI_BUILD_DIR/app
          ls $FCI_BUILD_DIR/app
          cat $FCI_BUILD_DIR/app/google-services.json
      - name: Clean Gradle Cache
        script: fastlane runClean
      - name: Run Unit Test
        script: fastlane runUnitTest
      - name: run UI Test
        script: echo "UI Test"
      - name: build
        script: fastlane runBuildApk
