workflows:
  my-workflow:
    environment:
      java: 17
    scripts:
      - name: Clean Gradle Cache
        script: fastlane runClean
      - name: Run Unit Test
        script: fastlane runUnitTest
      - name: run UI Test
        script: echo "UI Test"
      - name: build
        script: fastlane runBuildApk
