default_platform(:android)

platform :android do

  lane :runUnitTest do
    gradle(task:"test")
  end

  lane :runClean do
    gradle(task:"clean")
  end

  lane :runBuildApk do
    gradle(task:"assembleDebug")
  end

     ######## FIREBASE DISTRIBUTION  ########
    desc "Submit a new Google Test Build to Firebase App Distribution"
    lane :distribute do
            build_android_app(task:"clean assembleDebug")
            # build_android_app is a built-in fastlane action.
            release = firebase_app_distribution(
                app: "1:886936358353:android:0556937aa4ecaf36ba64f0",
                testers: "tester1@company.com",
                service_credentials_file: "fastlane/firebase_login_credentials.json",
                release_notes: "Lots of amazing new features to test out!"
            )
    end



end