default_platform(:android)

platform :android do

  lane :runUnitTest do
    gradle(task:"test")
  end

  lane :runClean do
    gradle(task:"clean")
  end

  lane :runBuildApk do
    gradle(task:"assembleDebug")
  end

  lane :build_for_screengrab do
    gradle(
      task: 'clean'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  lane :uiTest do
    gradle(task:"connectedDebugAndroidTest")
  end

end