default_platform(:android)

platform :android do

  lane :runUnitTest do
    gradle(task:"test")
  end

  lane :runClean do
    gradle(task:"clean")
  end

  lane :runBuildApk do
    gradle(task:"assembleDebug")
  end

desc "Build debug and test APK for screenshots"
  lane :build_and_screengrab do
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
    screengrab()
  end



     ######## FIREBASE DISTRIBUTION  ########
    desc "Submit a new Google Test Build to Firebase App Distribution"
    lane :distribute do |options|

            versionCode = ENV['Version_Code']
            versionName = ENV['Version_Name']
            increment_version_code({ version_code: versionCode})
            increment_version_name({version_name: versionName})
            gradle(task:'clean')
            gradle(task: 'assembleDebug',
            properties: {
                 "android.injected.version.name" => "5.0.0",
              }
            )
#             build_android_app(task:"clean assembleDebug", properties: {
#                                                                "android.injected.version.name" => versionName,
#                                                             })
            # build_android_app is a built-in fastlane action.
            release = firebase_app_distribution(
                app: "1:886936358353:android:0556937aa4ecaf36ba64f0",
                testers: "tester1@company.com",
                firebase_cli_token: "1//0gYN_CrG7jSwtCgYIARAAGBASNwF-L9IraKECfb4zm_kj_NjO3jKKN1164kGFesJtumayzBAjgl0bIozj-9hNfTXl0YFG-t2iNnI",
                release_notes: "Lots of amazing new features to test out!"
            )
    end



end